version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      SA_PASSWORD: "Password1234"
  adminer:
    image: adminer
    ports:
      - 8080:8080
