// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductServer.Models;

namespace ProductServer.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210920025255_V4_Seeding")]
    partial class V4_Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.Property<Guid>("CategoriesID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductsID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesID", "ProductsID");

                    b.HasIndex("ProductsID");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("4d8d2c0b-fb62-466d-97e4-03f45e96c50b")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("0e200b77-74c5-49b0-9a2f-6c8937f63c5b")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("20e4c639-07c4-431e-9c2d-2f3cf5e54c5b")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("edda4591-67d2-4698-aea3-9aea75c16e92")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("11b1cacd-ba0b-42f3-8d56-a6e69caee8bf")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("ca0b7956-5bf8-425c-b1d6-4dcc688df39c")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("2e154709-6a31-4f07-b430-ad0070f30767")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("5cdbccb6-6415-4148-9087-7f690d77e76e")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("315b03d9-7794-486d-8bca-a6f059602582")
                        },
                        new
                        {
                            CategoriesID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            ProductsID = new Guid("4f139e74-3785-45b7-be30-016eb3006b84")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("8abd528f-00b3-4575-a88f-00f9436e5c26")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("843b47e8-28bd-4e1d-851c-334490093ad2")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("c5df5ec3-c4cf-45ce-92fb-9c46e75ee242")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("a25ad2ef-b0a2-4db0-806e-8baabc9c8bf4")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("532a3a2c-3a3c-45fb-8917-b2b22680d0a5")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("3d2e3a4e-31d7-4a53-a264-724990d477b4")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("c0a054a1-a4de-4714-b0c4-5c5fe5c85ccb")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("5a6fde61-54eb-4a12-9b8d-cd8b764b8258")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("a6a260a2-e335-40d2-ae28-8341e7475615")
                        },
                        new
                        {
                            CategoriesID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            ProductsID = new Guid("c4b89587-38b8-4cd0-a346-5cac2ff84a7a")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("aa296adc-8f0c-412f-9182-71d71ee5adb8")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("edcfa79c-88fc-4fcb-a386-a83d88424c61")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("fe694d82-dc3f-456d-b373-73fc599b5b75")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("0e9d5579-0c11-4eb5-bb08-2edb4a7622c4")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("c8199e99-0514-4b30-8329-cfe629ace7c4")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("c8423efc-967c-4fee-9018-ffe599f965de")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("18f96215-987c-43f0-aa26-fa728919418e")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("222e4f86-09f7-41ed-8545-57be69ba9e13")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("f3276149-b21d-4a66-b23a-d2e579ef8f42")
                        },
                        new
                        {
                            CategoriesID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            ProductsID = new Guid("7b1ebcbb-da0a-4e5d-8899-aeb120e7fc95")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("e7034dc7-2a52-4f24-a86f-02d134dcb705")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("443a40d5-3114-454a-bbc4-0486591e9416")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("42c97850-04be-43c7-a7df-5fefaeed5c7e")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("62495399-1606-49fa-bb39-c22a93b326a2")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("71223077-7fdb-4d11-8bad-4ffe8acd7371")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("d703a4b7-2fa9-4582-852e-1c1aff538db4")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("044626ad-be04-4f57-9868-6c8c6c99972c")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("efe96324-d694-4228-bc29-1aef4b10e706")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("3fffaceb-6a0b-4676-9075-2667d0cd5f38")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("0ac4d331-c681-4382-8efe-7bdb9a176a2d")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("54a53467-b32c-4d47-8917-85f6d8cb3882")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("0fdbf451-1ad4-4276-9ec6-c7711210b936")
                        },
                        new
                        {
                            CategoriesID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            ProductsID = new Guid("33cbebb4-46a9-4028-9d7d-714bbb3426bc")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("06750427-2506-4cb6-a89b-6f1e36a80ccd")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("802a702a-be68-4ef6-9953-3669bd6c1d29")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("8551ac3d-5028-4fba-a4e1-87967b29dfa6")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("76e01e67-d2e3-48be-ae5f-6a30460206e7")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("db5a433f-b0e6-4f43-bc87-2c00c382b627")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("7efbd3dc-23a6-4c49-abe4-0706fc3f367c")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("e59b4568-f009-4b14-b749-15536f9ebb54")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("e825462b-fe82-4a4b-8f93-63ff41535e8f")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("99d6555a-4f59-4d33-b472-ed0779f95978")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("3ca3afa8-f4a2-4e6a-b8c6-8319d0ca76e3")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("4b3310be-bb9d-4eeb-b584-627b00fe9898")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("6d24ecc9-2fe7-4d4a-a805-2ffb7f2b409a")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("b65c835c-d85e-41c8-9d27-e7db1bada0ef")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("57bf3a0f-edda-4c86-a676-66769c630f20")
                        },
                        new
                        {
                            CategoriesID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            ProductsID = new Guid("1c29430b-84eb-47e9-a676-9717691b4bc3")
                        });
                });

            modelBuilder.Entity("ProductServer.Models.Auth", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID", "RefreshToken");

                    b.ToTable("Auth");
                });

            modelBuilder.Entity("ProductServer.Models.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("438abce7-1034-471c-bdc8-8cd6e865939a"),
                            Name = "Book"
                        },
                        new
                        {
                            ID = new Guid("ea76cc34-e8a5-4e91-899e-1edcde3dc869"),
                            Name = "Car"
                        },
                        new
                        {
                            ID = new Guid("2ee81735-67ce-4d68-aa49-c71034dd190a"),
                            Name = "Television"
                        },
                        new
                        {
                            ID = new Guid("d6866030-7f1c-4388-ad3e-5f06ba307e6f"),
                            Name = "Laptop"
                        },
                        new
                        {
                            ID = new Guid("99b5e2e3-aeea-404b-bf0c-ee2e1b4325b6"),
                            Name = "Mobile Phone"
                        });
                });

            modelBuilder.Entity("ProductServer.Models.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4d8d2c0b-fb62-466d-97e4-03f45e96c50b"),
                            Description = "product's short description",
                            Name = "The Hunger Games (The Hunger Games, #1)",
                            Price = 110.74397718102855,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2024, 5, 24, 21, 28, 41, 527, DateTimeKind.Utc).AddTicks(3992),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("0e200b77-74c5-49b0-9a2f-6c8937f63c5b"),
                            Description = "product's short description",
                            Name = "Suzanne Collins",
                            Price = 432.78260130099142,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2026, 2, 4, 0, 34, 57, 779, DateTimeKind.Utc).AddTicks(7621),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("20e4c639-07c4-431e-9c2d-2f3cf5e54c5b"),
                            Description = "product's short description",
                            Name = "Harry Potter and the Order of the Phoenix (Harry Potter, #5)",
                            Price = 642.4555553321054,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2019, 3, 28, 0, 36, 0, 838, DateTimeKind.Utc).AddTicks(7758),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("edda4591-67d2-4698-aea3-9aea75c16e92"),
                            Description = "product's short description",
                            Name = "J.K. Rowling",
                            Price = 989.76714768901797,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2023, 3, 31, 17, 11, 43, 793, DateTimeKind.Utc).AddTicks(7768),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("11b1cacd-ba0b-42f3-8d56-a6e69caee8bf"),
                            Description = "product's short description",
                            Name = "To Kill a Mockingbird",
                            Price = 615.34640826999509,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2023, 9, 16, 14, 6, 53, 338, DateTimeKind.Utc).AddTicks(7775),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("ca0b7956-5bf8-425c-b1d6-4dcc688df39c"),
                            Description = "product's short description",
                            Name = "Harper Lee",
                            Price = 93.388480643457015,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2020, 7, 22, 5, 10, 59, 423, DateTimeKind.Utc).AddTicks(7790),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("2e154709-6a31-4f07-b430-ad0070f30767"),
                            Description = "product's short description",
                            Name = "Pride and Prejudice",
                            Price = 169.46715310656799,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2019, 10, 27, 3, 24, 7, 864, DateTimeKind.Utc).AddTicks(7797),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("5cdbccb6-6415-4148-9087-7f690d77e76e"),
                            Description = "product's short description",
                            Name = "Jane Austen",
                            Price = 886.46954059902089,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2023, 11, 9, 8, 42, 1, 54, DateTimeKind.Utc).AddTicks(7803),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("315b03d9-7794-486d-8bca-a6f059602582"),
                            Description = "product's short description",
                            Name = "Twilight (The Twilight Saga, #1)",
                            Price = 13.614402624598892,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2024, 9, 26, 19, 20, 26, 591, DateTimeKind.Utc).AddTicks(7811),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("4f139e74-3785-45b7-be30-016eb3006b84"),
                            Description = "product's short description",
                            Name = "Stephenie Meyer",
                            Price = 62.503324850696764,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2021, 12, 20, 1, 11, 39, 708, DateTimeKind.Utc).AddTicks(7820),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("8abd528f-00b3-4575-a88f-00f9436e5c26"),
                            Description = "product's short description",
                            Name = "Abarth",
                            Price = 993.79634996587242,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2020, 8, 7, 22, 27, 35, 619, DateTimeKind.Utc).AddTicks(7837),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("843b47e8-28bd-4e1d-851c-334490093ad2"),
                            Description = "product's short description",
                            Name = "Acura",
                            Price = 675.40553010786209,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2021, 6, 14, 11, 15, 16, 694, DateTimeKind.Utc).AddTicks(7845),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("c5df5ec3-c4cf-45ce-92fb-9c46e75ee242"),
                            Description = "product's short description",
                            Name = "Alfa Romeo",
                            Price = 353.48411060566275,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2018, 6, 18, 1, 23, 58, 734, DateTimeKind.Utc).AddTicks(7852),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("a25ad2ef-b0a2-4db0-806e-8baabc9c8bf4"),
                            Description = "product's short description",
                            Name = "Aston Martin",
                            Price = 691.694964511178,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2018, 4, 28, 3, 4, 58, 810, DateTimeKind.Utc).AddTicks(7858),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("532a3a2c-3a3c-45fb-8917-b2b22680d0a5"),
                            Description = "product's short description",
                            Name = "Audi",
                            Price = 85.039602166525839,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2021, 8, 8, 2, 33, 8, 834, DateTimeKind.Utc).AddTicks(7864),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("3d2e3a4e-31d7-4a53-a264-724990d477b4"),
                            Description = "product's short description",
                            Name = "Bentley",
                            Price = 46.855521410170724,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2018, 11, 28, 9, 20, 7, 219, DateTimeKind.Utc).AddTicks(7871),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("c0a054a1-a4de-4714-b0c4-5c5fe5c85ccb"),
                            Description = "product's short description",
                            Name = "BMW",
                            Price = 311.90280537675261,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2019, 10, 24, 12, 6, 46, 975, DateTimeKind.Utc).AddTicks(7877),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("5a6fde61-54eb-4a12-9b8d-cd8b764b8258"),
                            Description = "product's short description",
                            Name = "Buick",
                            Price = 875.82151399730776,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2018, 12, 17, 22, 23, 59, 74, DateTimeKind.Utc).AddTicks(7885),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("a6a260a2-e335-40d2-ae28-8341e7475615"),
                            Description = "product's short description",
                            Name = "Cadillac",
                            Price = 178.99329130490929,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2026, 3, 19, 15, 44, 6, 845, DateTimeKind.Utc).AddTicks(7891),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("c4b89587-38b8-4cd0-a346-5cac2ff84a7a"),
                            Description = "product's short description",
                            Name = "Chevrolet",
                            Price = 774.29170150975312,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2017, 12, 31, 6, 31, 31, 80, DateTimeKind.Utc).AddTicks(7935),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("aa296adc-8f0c-412f-9182-71d71ee5adb8"),
                            Description = "product's short description",
                            Name = "Acer",
                            Price = 320.90894008097655,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2021, 6, 2, 11, 30, 40, 598, DateTimeKind.Utc).AddTicks(7944),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("edcfa79c-88fc-4fcb-a386-a83d88424c61"),
                            Description = "product's short description",
                            Name = "Alba",
                            Price = 386.87502890214091,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2016, 11, 12, 11, 35, 49, 290, DateTimeKind.Utc).AddTicks(7951),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("fe694d82-dc3f-456d-b373-73fc599b5b75"),
                            Description = "product's short description",
                            Name = "Audiovox",
                            Price = 836.59599294727479,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2024, 6, 1, 10, 54, 26, 614, DateTimeKind.Utc).AddTicks(7957),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("0e9d5579-0c11-4eb5-bb08-2edb4a7622c4"),
                            Description = "product's short description",
                            Name = "BPL india lmt",
                            Price = 26.342012931752024,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2019, 1, 7, 14, 39, 31, 280, DateTimeKind.Utc).AddTicks(7964),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("c8199e99-0514-4b30-8329-cfe629ace7c4"),
                            Description = "product's short description",
                            Name = "Bush",
                            Price = 476.30751481107785,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2017, 12, 30, 20, 55, 51, 690, DateTimeKind.Utc).AddTicks(7971),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("c8423efc-967c-4fee-9018-ffe599f965de"),
                            Description = "product's short description",
                            Name = "Element",
                            Price = 370.88594463229458,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2020, 6, 4, 10, 19, 23, 553, DateTimeKind.Utc).AddTicks(7978),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("18f96215-987c-43f0-aa26-fa728919418e"),
                            Description = "product's short description",
                            Name = "Emerson",
                            Price = 306.02674712707602,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2018, 6, 11, 11, 2, 55, 200, DateTimeKind.Utc).AddTicks(7984),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("222e4f86-09f7-41ed-8545-57be69ba9e13"),
                            Description = "product's short description",
                            Name = "Gradiente",
                            Price = 439.16100284045609,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2018, 7, 10, 1, 58, 40, 194, DateTimeKind.Utc).AddTicks(7990),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("f3276149-b21d-4a66-b23a-d2e579ef8f42"),
                            Description = "product's short description",
                            Name = "Hannspree",
                            Price = 851.11425763513625,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2019, 12, 5, 5, 51, 40, 995, DateTimeKind.Utc).AddTicks(7997),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("7b1ebcbb-da0a-4e5d-8899-aeb120e7fc95"),
                            Description = "product's short description",
                            Name = "Heath Company",
                            Price = 651.28952621076701,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2023, 9, 7, 12, 31, 10, 43, DateTimeKind.Utc).AddTicks(8003),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("e7034dc7-2a52-4f24-a86f-02d134dcb705"),
                            Description = "product's short description",
                            Name = "Omen",
                            Price = 541.13244569913138,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2018, 5, 19, 18, 46, 30, 341, DateTimeKind.Utc).AddTicks(8012),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("443a40d5-3114-454a-bbc4-0486591e9416"),
                            Description = "product's short description",
                            Name = "Pavilion",
                            Price = 22.440291020292925,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2017, 7, 11, 17, 14, 29, 416, DateTimeKind.Utc).AddTicks(8019),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("42c97850-04be-43c7-a7df-5fefaeed5c7e"),
                            Description = "product's short description",
                            Name = "ZBook",
                            Price = 203.0018801814885,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2025, 12, 1, 15, 15, 17, 813, DateTimeKind.Utc).AddTicks(8026),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("62495399-1606-49fa-bb39-c22a93b326a2"),
                            Description = "product's short description",
                            Name = "Spectre",
                            Price = 825.20602775048746,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2017, 12, 26, 10, 31, 18, 716, DateTimeKind.Utc).AddTicks(8034),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("71223077-7fdb-4d11-8bad-4ffe8acd7371"),
                            Description = "product's short description",
                            Name = "Vostro",
                            Price = 694.0122571280283,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2017, 4, 29, 4, 54, 38, 807, DateTimeKind.Utc).AddTicks(8040),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("d703a4b7-2fa9-4582-852e-1c1aff538db4"),
                            Description = "product's short description",
                            Name = "MacBook",
                            Price = 202.55167419209687,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2018, 7, 23, 15, 17, 31, 127, DateTimeKind.Utc).AddTicks(8046),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("044626ad-be04-4f57-9868-6c8c6c99972c"),
                            Description = "product's short description",
                            Name = "VivoBook",
                            Price = 680.91972343666464,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2019, 2, 18, 22, 58, 56, 518, DateTimeKind.Utc).AddTicks(8085),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("efe96324-d694-4228-bc29-1aef4b10e706"),
                            Description = "product's short description",
                            Name = "ROG",
                            Price = 568.16922713451515,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2018, 12, 23, 3, 25, 38, 456, DateTimeKind.Utc).AddTicks(8092),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("3fffaceb-6a0b-4676-9075-2667d0cd5f38"),
                            Description = "product's short description",
                            Name = "Pixelbook",
                            Price = 601.18403406868879,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2022, 7, 25, 1, 31, 5, 801, DateTimeKind.Utc).AddTicks(8098),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("0ac4d331-c681-4382-8efe-7bdb9a176a2d"),
                            Description = "product's short description",
                            Name = "Pixelbook Go",
                            Price = 313.68857310790963,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2022, 1, 23, 18, 12, 5, 736, DateTimeKind.Utc).AddTicks(8105),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("54a53467-b32c-4d47-8917-85f6d8cb3882"),
                            Description = "product's short description",
                            Name = "Gram",
                            Price = 993.86399052751437,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2017, 5, 19, 2, 49, 31, 684, DateTimeKind.Utc).AddTicks(8111),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("0fdbf451-1ad4-4276-9ec6-c7711210b936"),
                            Description = "product's short description",
                            Name = "VAIO",
                            Price = 827.01951257280052,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2019, 11, 14, 0, 39, 11, 251, DateTimeKind.Utc).AddTicks(8118),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("33cbebb4-46a9-4028-9d7d-714bbb3426bc"),
                            Description = "product's short description",
                            Name = "HTC",
                            Price = 874.76672645414567,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2019, 8, 26, 14, 26, 23, 738, DateTimeKind.Utc).AddTicks(8125),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("06750427-2506-4cb6-a89b-6f1e36a80ccd"),
                            Description = "product's short description",
                            Name = "Apple iPhone 12 Pro Max",
                            Price = 800.38987137395407,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2024, 1, 29, 6, 11, 18, 729, DateTimeKind.Utc).AddTicks(8132),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("802a702a-be68-4ef6-9953-3669bd6c1d29"),
                            Description = "product's short description",
                            Name = "Rs. 115,900",
                            Price = 508.71412619422853,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2020, 2, 16, 11, 50, 12, 790, DateTimeKind.Utc).AddTicks(8139),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("8551ac3d-5028-4fba-a4e1-87967b29dfa6"),
                            Description = "product's short description",
                            Name = "Xiaomi Mi 11 Ultra",
                            Price = 893.646356600172,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2023, 12, 7, 13, 16, 50, 343, DateTimeKind.Utc).AddTicks(8145),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("76e01e67-d2e3-48be-ae5f-6a30460206e7"),
                            Description = "product's short description",
                            Name = "Rs. 70,999",
                            Price = 861.34661494816964,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2025, 5, 23, 15, 26, 47, 707, DateTimeKind.Utc).AddTicks(8151),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("db5a433f-b0e6-4f43-bc87-2c00c382b627"),
                            Description = "product's short description",
                            Name = "Samsung Galaxy S21 Ultra",
                            Price = 410.3301793384972,
                            Rating = (short)3,
                            ReleaseDate = new DateTime(2022, 1, 14, 4, 8, 9, 649, DateTimeKind.Utc).AddTicks(8158),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("7efbd3dc-23a6-4c49-abe4-0706fc3f367c"),
                            Description = "product's short description",
                            Name = "Rs. 105,040",
                            Price = 377.3049653402087,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2019, 12, 28, 10, 49, 39, 173, DateTimeKind.Utc).AddTicks(8164),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("e59b4568-f009-4b14-b749-15536f9ebb54"),
                            Description = "product's short description",
                            Name = "Samsung Galaxy Z Fold 3",
                            Price = 685.15585301684018,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2019, 4, 27, 19, 25, 52, 278, DateTimeKind.Utc).AddTicks(8171),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("e825462b-fe82-4a4b-8f93-63ff41535e8f"),
                            Description = "product's short description",
                            Name = "Rs. 149,999",
                            Price = 324.10512041491694,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2018, 4, 29, 7, 30, 6, 620, DateTimeKind.Utc).AddTicks(8177),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("99d6555a-4f59-4d33-b472-ed0779f95978"),
                            Description = "product's short description",
                            Name = "Samsung Galaxy Z Flip 3",
                            Price = 951.68983654663418,
                            Rating = (short)0,
                            ReleaseDate = new DateTime(2024, 11, 19, 22, 27, 10, 242, DateTimeKind.Utc).AddTicks(8183),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        },
                        new
                        {
                            ID = new Guid("3ca3afa8-f4a2-4e6a-b8c6-8319d0ca76e3"),
                            Description = "product's short description",
                            Name = "Rs. 84,999",
                            Price = 441.46957594969757,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2018, 7, 5, 1, 13, 0, 295, DateTimeKind.Utc).AddTicks(8190),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("4b3310be-bb9d-4eeb-b584-627b00fe9898"),
                            Description = "product's short description",
                            Name = "Asus ROG Phone 5",
                            Price = 10.90355776758099,
                            Rating = (short)1,
                            ReleaseDate = new DateTime(2019, 7, 24, 17, 24, 8, 221, DateTimeKind.Utc).AddTicks(8196),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("6d24ecc9-2fe7-4d4a-a805-2ffb7f2b409a"),
                            Description = "product's short description",
                            Name = "Rs. 49,999",
                            Price = 150.29569675694017,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2021, 9, 1, 9, 9, 8, 467, DateTimeKind.Utc).AddTicks(8261),
                            SupplierID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361")
                        },
                        new
                        {
                            ID = new Guid("b65c835c-d85e-41c8-9d27-e7db1bada0ef"),
                            Description = "product's short description",
                            Name = "Vivo X60 Pro Plus",
                            Price = 829.07021037725269,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2021, 3, 5, 19, 27, 45, 757, DateTimeKind.Utc).AddTicks(8270),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("57bf3a0f-edda-4c86-a676-66769c630f20"),
                            Description = "product's short description",
                            Name = "Rs. 69,990",
                            Price = 939.92799424562975,
                            Rating = (short)2,
                            ReleaseDate = new DateTime(2020, 5, 10, 12, 40, 46, 483, DateTimeKind.Utc).AddTicks(8276),
                            SupplierID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201")
                        },
                        new
                        {
                            ID = new Guid("1c29430b-84eb-47e9-a676-9717691b4bc3"),
                            Description = "product's short description",
                            Name = "OnePlus 9 Pro",
                            Price = 56.341407846818406,
                            Rating = (short)4,
                            ReleaseDate = new DateTime(2017, 11, 20, 1, 51, 2, 7, DateTimeKind.Utc).AddTicks(8283),
                            SupplierID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36")
                        });
                });

            modelBuilder.Entity("ProductServer.Models.ProductDetail", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            ProductID = new Guid("4d8d2c0b-fb62-466d-97e4-03f45e96c50b"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("0e200b77-74c5-49b0-9a2f-6c8937f63c5b"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("20e4c639-07c4-431e-9c2d-2f3cf5e54c5b"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("edda4591-67d2-4698-aea3-9aea75c16e92"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("11b1cacd-ba0b-42f3-8d56-a6e69caee8bf"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("ca0b7956-5bf8-425c-b1d6-4dcc688df39c"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("2e154709-6a31-4f07-b430-ad0070f30767"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("5cdbccb6-6415-4148-9087-7f690d77e76e"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("315b03d9-7794-486d-8bca-a6f059602582"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("4f139e74-3785-45b7-be30-016eb3006b84"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("8abd528f-00b3-4575-a88f-00f9436e5c26"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("843b47e8-28bd-4e1d-851c-334490093ad2"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("c5df5ec3-c4cf-45ce-92fb-9c46e75ee242"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("a25ad2ef-b0a2-4db0-806e-8baabc9c8bf4"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("532a3a2c-3a3c-45fb-8917-b2b22680d0a5"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("3d2e3a4e-31d7-4a53-a264-724990d477b4"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("c0a054a1-a4de-4714-b0c4-5c5fe5c85ccb"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("5a6fde61-54eb-4a12-9b8d-cd8b764b8258"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("a6a260a2-e335-40d2-ae28-8341e7475615"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("c4b89587-38b8-4cd0-a346-5cac2ff84a7a"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("aa296adc-8f0c-412f-9182-71d71ee5adb8"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("edcfa79c-88fc-4fcb-a386-a83d88424c61"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("fe694d82-dc3f-456d-b373-73fc599b5b75"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("0e9d5579-0c11-4eb5-bb08-2edb4a7622c4"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("c8199e99-0514-4b30-8329-cfe629ace7c4"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("c8423efc-967c-4fee-9018-ffe599f965de"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("18f96215-987c-43f0-aa26-fa728919418e"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("222e4f86-09f7-41ed-8545-57be69ba9e13"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("f3276149-b21d-4a66-b23a-d2e579ef8f42"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("7b1ebcbb-da0a-4e5d-8899-aeb120e7fc95"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("e7034dc7-2a52-4f24-a86f-02d134dcb705"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("443a40d5-3114-454a-bbc4-0486591e9416"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("42c97850-04be-43c7-a7df-5fefaeed5c7e"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("62495399-1606-49fa-bb39-c22a93b326a2"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("71223077-7fdb-4d11-8bad-4ffe8acd7371"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("d703a4b7-2fa9-4582-852e-1c1aff538db4"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("044626ad-be04-4f57-9868-6c8c6c99972c"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("efe96324-d694-4228-bc29-1aef4b10e706"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("3fffaceb-6a0b-4676-9075-2667d0cd5f38"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("0ac4d331-c681-4382-8efe-7bdb9a176a2d"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("54a53467-b32c-4d47-8917-85f6d8cb3882"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("0fdbf451-1ad4-4276-9ec6-c7711210b936"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("33cbebb4-46a9-4028-9d7d-714bbb3426bc"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("06750427-2506-4cb6-a89b-6f1e36a80ccd"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("802a702a-be68-4ef6-9953-3669bd6c1d29"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("8551ac3d-5028-4fba-a4e1-87967b29dfa6"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("76e01e67-d2e3-48be-ae5f-6a30460206e7"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("db5a433f-b0e6-4f43-bc87-2c00c382b627"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("7efbd3dc-23a6-4c49-abe4-0706fc3f367c"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("e59b4568-f009-4b14-b749-15536f9ebb54"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("e825462b-fe82-4a4b-8f93-63ff41535e8f"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("99d6555a-4f59-4d33-b472-ed0779f95978"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("3ca3afa8-f4a2-4e6a-b8c6-8319d0ca76e3"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("4b3310be-bb9d-4eeb-b584-627b00fe9898"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("6d24ecc9-2fe7-4d4a-a805-2ffb7f2b409a"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("b65c835c-d85e-41c8-9d27-e7db1bada0ef"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("57bf3a0f-edda-4c86-a676-66769c630f20"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        },
                        new
                        {
                            ProductID = new Guid("1c29430b-84eb-47e9-a676-9717691b4bc3"),
                            Detail = "Cum facere tenetur aut cupiditate sint qui explicabo consequatur et possimus velit. Hic consequuntur labore in velit dolores et iusto autem vel provident. Eum voluptatem quos qui iste pariatur aut consequatur reprehenderit ad fugiat ipsum. Qui vitae veritatis quo nesciunt itaque sed dolorem aperiam ab quod quisquam ut tempora officia. "
                        });
                });

            modelBuilder.Entity("ProductServer.Models.Supplier", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("de7dfb6d-a4cb-40fa-8589-9f92c2f51361"),
                            Address = "Ho Chi Minh City",
                            Name = "Alpha"
                        },
                        new
                        {
                            ID = new Guid("3bc7c37d-06ee-408f-ac34-32d574121a36"),
                            Address = "Ha Noi City",
                            Name = "Beta"
                        },
                        new
                        {
                            ID = new Guid("ae0a77b1-72dd-4f7a-8236-ca4860a75201"),
                            Address = "Da Nang City",
                            Name = "Delta"
                        });
                });

            modelBuilder.Entity("ProductServer.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a814ae1c-733f-46c4-a230-261e39072f6e"),
                            DisplayName = "Tuan Nguyen",
                            HashedPassword = "$2a$13$xk2HTLFXnufoUgKKDrNeL.pT.6o.3tBcpQcfztHuIQ4Umyokg6.7a"
                        });
                });

            modelBuilder.Entity("CategoryProduct", b =>
                {
                    b.HasOne("ProductServer.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductServer.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductServer.Models.Auth", b =>
                {
                    b.HasOne("ProductServer.Models.User", "User")
                        .WithMany("Auths")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductServer.Models.Product", b =>
                {
                    b.HasOne("ProductServer.Models.ProductDetail", "ProductDetail")
                        .WithMany()
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProductServer.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductDetail");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProductServer.Models.User", b =>
                {
                    b.Navigation("Auths");
                });
#pragma warning restore 612, 618
        }
    }
}
